# Configuration for guesswho.yosept.me
[build]
  command = "bunx nx build guess-who"
  publish = "dist/apps/guess-who"

[build.environment]
  NODE_VERSION = "18"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200